// tableData.js

export const headers = [
  {
    key: 'entidad',
    header: 'Entidad',
  },
  {
    key: 'producto',
    header: 'Producto',
  },
  {
    key: 'caso',
    header: 'Case number',
  },
  {
    key: 'status',
    header: 'Status',
  },
  {
    key: 'descripcion',
    header: 'Status description',
  },
  {
    key: 'abiertoEn',
    header: 'Open date',
  },
  {
    key: 'ultimaIteracion',
    header: 'Last altered',
  },
  {
    key: 'daysOpen',
    header: 'Days open',
  },
];

export const rows = [
  {
    id: 'row0',
    entidad: 'Entidad 1',
    producto: 'Producto 1',
    caso: 'Caso 1',
    status: 'Status 1',
    descripcion: 'Descripción 1 esta es una descripcion muy muy larga',
    abiertoEn: 'Abierto en 1',
    ultimaIteracion: 'Iteración 1',
    daysOpen: '5',
  },
  {
    id: 'row1',
    entidad: 'Entidad 2',
    producto: 'Producto 2',
    caso: 'Caso 2',
    status: 'Status 2',
    descripcion: 'Descripción 2',
    abiertoEn: 'Abierto en 2',
    ultimaIteracion: 'Iteración 2',
    daysOpen: '10',
  },
  {
    id: 'row2',
    entidad: 'Entidad 3',
    producto: 'Producto 3',
    caso: 'Caso 3',
    status: 'Status 3',
    descripcion: 'Descripción 3',
    abiertoEn: 'Abierto en 3',
    ultimaIteracion: 'Iteración 3',
    daysOpen: '15',
  },
  {
    id: 'row3',
    entidad: 'Entidad 4',
    producto: 'Producto 4',
    caso: 'Caso 4',
    status: 'Status 4',
    descripcion: 'Descripción 4',
    abiertoEn: 'Abierto en 4',
    ultimaIteracion: 'Iteración 4',
    daysOpen: '20',
  },
  {
    id: 'row4',
    entidad: 'Entidad 5',
    producto: 'Producto 5',
    caso: 'Caso 5',
    status: 'Status 5',
    descripcion: 'Descripción 5',
    abiertoEn: 'Abierto en 5',
    ultimaIteracion: 'Iteración 5',
    daysOpen: '25',
  },
  {
    id: 'row5',
    entidad: 'Entidad 6',
    producto: 'Producto 6',
    caso: 'Caso 6',
    status: 'Status 6',
    descripcion: 'Descripción 6',
    abiertoEn: 'Abierto en 6',
    ultimaIteracion: 'Iteración 6',
    daysOpen: '30',
  },
  {
    id: 'row6',
    entidad: 'Entidad 7',
    producto: 'Producto 7',
    caso: 'Caso 7',
    status: 'Status 7',
    descripcion: 'Descripción 7',
    abiertoEn: 'Abierto en 7',
    ultimaIteracion: 'Iteración 7',
    daysOpen: '35',
  },
  {
    id: 'row7',
    entidad: 'Entidad 8',
    producto: 'Producto 8',
    caso: 'Caso 8',
    status: 'Status 8',
    descripcion: 'Descripción 8',
    abiertoEn: 'Abierto en 8',
    ultimaIteracion: 'Iteración 8',
    daysOpen: '40',
  },
  {
    id: 'row8',
    entidad: 'Entidad 9',
    producto: 'Producto 9',
    caso: 'Caso 9',
    status: 'Status 9',
    descripcion: 'Descripción 9',
    abiertoEn: 'Abierto en 9',
    ultimaIteracion: 'Iteración 9',
    daysOpen: '45',
  },
  {
    id: 'row9',
    entidad: 'Entidad 10',
    producto: 'Producto 10',
    caso: 'Caso 10',
    status: 'Status 10',
    descripcion: 'Descripción 10',
    abiertoEn: 'Abierto en 10',
    ultimaIteracion: 'Iteración 10',
    daysOpen: '50',
  },
];
